### ISSUE TITLE
Is this package compatible with cellranger output ?

### ISSUE THREAD

**Issue by Romeo1-1** [deepomicslab/SeCNV#1]
Hello,

First, thank you for this package ! I tried to run an analysis on a sample that was pre-processed with Cellranger (i started directly with SeCNV.py on my possorted_bam.bam file) and i got this error (screenshot joined).

![AAA](https://user-images.githubusercontent.com/101837631/166819900-414e5e2d-147d-4556-9c99-0f66e28835e8.JPG)

I tried to use the same reference as you (= the hg38.fa file i found on your GDrive) and then another one i processed myself, just to be sure. I got the same error twice.

Do you think it is because i used Cellranger to pre-process those files ? Because i'm sure there are normal cells in this sample, i was able to detect them with Loupe, CHISEL, Copykit or other packages.

Thank you in advance,

**Comment by wangruohan111** [comment]
Hi, I am sorry I made a mistake in the warning, and it should be "Please make sure the bin size is 500 kb.". Therefore, please try the command with -b 500000. Please let me know if there is any problem.

**Comment by Romeo1-1** [comment]
Hi, i'll definitly try and tell you how it went, but is it possible to use lower bin size than 500 000 in this scenario ?

**Comment by wangruohan111** [comment]
I have uploaded some bam files for normal cells into the Google drive, and you can put them together with your samples. In this case, SeCNV can use the normal cells for bias correction and you can set the bin size as you want.

**Comment by Romeo1-1** [comment]
Hello @wangruohan111,

I'm sorry for the delay, I had another project to work on. I started working again on CNV a few days ago, I finally tried again your package and it worked perfectly !

I just have 3 questions: 
- After being processed with CellRanger, 10X bam files are aligned but come with every cell in one bam file. Should I "splice" them to have only 1 cell per bam file ? In that case, would it be possible to "mix" cells from 2 samples and be able to know downstream from which sample they came from ?
- I feel a bit overwhelmed with the output files. I know that some packages are using the cell x bin matrix as input but what would you personnally recommend for downstream analysis ? I noticed that scSVAS (https://sc.deepomics.org/) from your lab is down right now (at least in my country)
- That's more of a general question and may also be very dumb. CellRanger at the end of his output offer a h5 from which you can extract a cell x bin matrix. How does your program compare to this "output", should I expect to see differences ?

Thank you a lot for your time

**Comment by wangruohan111** [comment]
Hello,

There are my answers to your questions.

First, I recommend you divide the bam file into "one cell per bam file", otherwise SeCNV can only give the predictions based on the pooling information and it is not likely to know what cell the CNVs come from.

Second, scSVAS has been under maintenance recently, so please try other software or websites for your analysis. I will inform you as soon as scSVAS is ready to use.

Third, I quickly go through the tutorial of CellRanger, and it seems that CellRanger is mainly used for scRNA-seq data whereas SeCNV is based on scDNA-seq data. What kind of data do you have? 

Thanks for your interest in SeCNV.

**Comment by wangruohan111** [comment]
Hi, scSVAS is ready to use.
