### ISSUE TITLE
indentation error

### ISSUE THREAD

**Issue by volcano1998** [deepomicslab/SeCNV#3]
Hi dear author,
       when I try to run your code, I found that there might be an error in your code: call_cn.py, line 156, you might want to remove a tab there, so that the input of KR_norm would be a symmetric matrix.
      In the original code, I experienced the issue of long iteration and all nan output, after changing this, I was able to reproduce your result. Hope this would be helpful.

**Comment by wangruohan111** [comment]
Hi,

Thanks for noticing and correcting the bug. Yes, there is a redundant tab on line 156. However, the tab does not exist in my scripts in the local repository, and it disappears again when I download the scripts from GitHub. I don't know why @_@. 

Anyway, thanks for your reminder. It is very helpful for other users. 

Best regards,
Ruohan

**Comment by volcano1998** [comment]
You are welcome! btw I saw you updated that code, but when I clicked on it, somehow the tab is still there..... You might want to double-check if your commit is successful...

**Comment by wangruohan111** [comment]
Hi, the script is updated successfully now. Thanks for your interest in SeCNV.
